"""
EKAM Rubric Service

Per-round scoring rubrics. Each round has a set of criteria; a judge scores
each criterion up to its max_score and the evaluation total is the sum.

- Sensible defaults are seeded the first time a round's rubric is requested.
- Criteria are fully organizer-editable.
- Criteria can optionally be (re)generated by AI from the event/round context.
"""

import asyncio
import json

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.event import Round, Event
from app.models.rubric import RubricCriterion


# Default rubric — max_score values sum to 100 so totals stay on a 0–100 scale
# (keeps leaderboard / anomaly thresholds consistent).
_DEFAULT_CRITERIA = [
    ("Understanding of Problem", "Clarity of the problem and depth of understanding.", 15),
    ("Completion of MVP", "How complete and functional the core build is.", 20),
    ("Extra Features", "Additional features beyond the core MVP.", 10),
    ("Individual Member Contribution", "Evidence of contribution from each member.", 10),
    ("Teamwork", "Collaboration and coordination within the team.", 10),
    ("Design", "UI/UX quality and overall design polish.", 10),
    ("Product Understanding", "Grasp of the product, users, and market.", 10),
    ("Scalability", "Ability of the solution to scale.", 8),
    ("Viability", "Real-world feasibility and sustainability.", 7),
]


async def _get_round(db: AsyncSession, round_id) -> Round:
    rnd = (
        await db.execute(select(Round).where(Round.id == round_id))
    ).scalars().first()
    if not rnd:
        raise HTTPException(status_code=404, detail="Round not found")
    return rnd


async def _seed_default_criteria(db: AsyncSession, round_id) -> list[RubricCriterion]:
    criteria = [
        RubricCriterion(
            round_id=round_id,
            name=name,
            description=description,
            max_score=float(max_score),
            position=index,
        )
        for index, (name, description, max_score) in enumerate(_DEFAULT_CRITERIA)
    ]
    db.add_all(criteria)
    await db.commit()
    for c in criteria:
        await db.refresh(c)
    return criteria


async def list_criteria(
    db: AsyncSession,
    round_id,
    seed_if_empty: bool = True,
) -> list[RubricCriterion]:
    result = await db.execute(
        select(RubricCriterion)
        .where(RubricCriterion.round_id == round_id)
        .order_by(RubricCriterion.position, RubricCriterion.created_at)
    )
    criteria = list(result.scalars().all())

    if not criteria and seed_if_empty:
        await _get_round(db, round_id)  # 404 if the round doesn't exist
        criteria = await _seed_default_criteria(db, round_id)

    return criteria


async def create_criterion(db: AsyncSession, round_id, data) -> RubricCriterion:
    await _get_round(db, round_id)
    criterion = RubricCriterion(
        round_id=round_id,
        name=data.name,
        description=data.description,
        max_score=float(data.max_score),
        position=data.position,
    )
    db.add(criterion)
    await db.commit()
    await db.refresh(criterion)
    return criterion


async def update_criterion(db: AsyncSession, criterion_id, data) -> RubricCriterion:
    criterion = (
        await db.execute(
            select(RubricCriterion).where(RubricCriterion.id == criterion_id)
        )
    ).scalars().first()
    if not criterion:
        raise HTTPException(status_code=404, detail="Criterion not found")

    if data.name is not None:
        criterion.name = data.name
    if data.description is not None:
        criterion.description = data.description
    if data.max_score is not None:
        criterion.max_score = float(data.max_score)
    if data.position is not None:
        criterion.position = data.position

    await db.commit()
    await db.refresh(criterion)
    return criterion


async def delete_criterion(db: AsyncSession, criterion_id) -> None:
    criterion = (
        await db.execute(
            select(RubricCriterion).where(RubricCriterion.id == criterion_id)
        )
    ).scalars().first()
    if not criterion:
        raise HTTPException(status_code=404, detail="Criterion not found")
    await db.delete(criterion)
    await db.commit()


def _clean_json(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 2)[1] if raw.count("```") >= 2 else raw[3:]
        if raw.startswith("json"):
            raw = raw[4:]
    return raw.strip().strip("`").strip()


def _generate_criteria_sync(model: str, api_key: str, context: str) -> list[dict]:
    from groq import Groq

    client = Groq(api_key=api_key)
    prompt = f"""You design judging rubrics for hackathons/competitions.

Given this event/round context:
{context}

Return ONLY a JSON array (no markdown) of 6-10 scoring criteria tailored to the
theme. Each item: {{"name": str, "description": str (one line), "max_score": int}}.
The max_score values MUST sum to exactly 100. Always include criteria covering:
problem understanding, MVP completion, teamwork, design, scalability, viability.
"""
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=900,
    )
    raw = _clean_json(response.choices[0].message.content or "")
    data = json.loads(raw)
    if isinstance(data, dict) and "criteria" in data:
        data = data["criteria"]
    if not isinstance(data, list):
        raise ValueError("AI did not return a list")
    return data


async def generate_criteria_with_ai(db: AsyncSession, round_id) -> list[RubricCriterion]:
    """(Re)generate a round's rubric from the event context using Groq.

    Replaces existing criteria ONLY when the AI returns a usable rubric. If Groq
    is unavailable or returns junk, the round's current rubric is left untouched
    (or seeded with defaults if it had none) — so a failed regenerate never
    destroys a hand-made rubric.
    """
    rnd = await _get_round(db, round_id)
    event = (
        await db.execute(select(Event).where(Event.id == rnd.event_id))
    ).scalars().first()

    context = (
        f"Event: {event.name if event else ''}\n"
        f"Type: {getattr(event, 'type', '') if event else ''}\n"
        f"Description: {getattr(event, 'description', '') or '' if event else ''}\n"
        f"Round: {rnd.name}\n"
    )

    api_key = getattr(settings, "GROQ_API_KEY", None)
    model = getattr(settings, "GROQ_MODEL", None) or "llama-3.3-70b-versatile"

    parsed: list[dict] | None = None
    if api_key:
        try:
            parsed = await asyncio.to_thread(
                _generate_criteria_sync, model, api_key, context
            )
        except Exception as exc:
            print(f"[rubric_service] AI rubric generation failed: {exc}")
            parsed = None

    # Build the new criteria from the AI output FIRST — only if we get a usable
    # rubric do we touch the existing one.
    new_criteria = []
    if parsed:
        for index, item in enumerate(parsed):
            try:
                name = str(item["name"]).strip()
                if not name:
                    continue
                new_criteria.append(
                    RubricCriterion(
                        round_id=round_id,
                        name=name[:120],
                        description=(str(item.get("description") or "")[:300]) or None,
                        max_score=float(item.get("max_score") or 10),
                        position=index,
                    )
                )
            except Exception:
                continue

    if new_criteria:
        # Successful AI rubric — now it's safe to replace the old one.
        existing = (
            await db.execute(
                select(RubricCriterion).where(RubricCriterion.round_id == round_id)
            )
        ).scalars().all()
        for c in existing:
            await db.delete(c)
        await db.flush()

        db.add_all(new_criteria)
        await db.commit()
        for c in new_criteria:
            await db.refresh(c)
        return new_criteria

    # AI failed or returned junk — DON'T destroy the existing rubric. Return what's
    # already there; only seed defaults if the round has no rubric at all.
    return await list_criteria(db, round_id, seed_if_empty=True)


async def total_max_for_round(db: AsyncSession, round_id) -> float:
    criteria = await list_criteria(db, round_id, seed_if_empty=False)
    return sum(c.max_score for c in criteria)
