"""
EKAM Winner Service

Proposes winners (top-N by score from the latest round's leaderboard) and,
once the organizer confirms, announces them: sends each winning team a
congratulations + prize/next-steps email with a winner certificate attached,
distributes participation certificates to everyone, and records the result.
"""

import asyncio

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.certificate import generate_certificate_html
from app.models.event import Event, Round
from app.models.participant import Participant
from app.models.report import Report as ReportModel
from app.models.team import Team, TeamMember
from app.services.email_service import send_direct_email
from app.services.leaderboard_service import generate_leaderboard_service


def _ordinal(n: int) -> str:
    if 10 <= (n % 100) <= 20:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _esc(text) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _winners_report_html(event, winners: list[dict]) -> str:
    """A formatted (non-JSON) winners report for the Reports viewer."""
    medals = {1: "🥇", 2: "🥈", 3: "🥉"}
    rows = []
    for w in sorted(winners, key=lambda x: x.get("rank") or 999):
        rank = int(w.get("rank") or 0)
        badge = medals.get(rank, f"#{rank}" if rank else "—")
        score = w.get("score")
        score_txt = f"{float(score):.1f}" if score is not None else "—"
        prize = _esc(w.get("prize") or "")
        rows.append(
            f"<tr>"
            f"<td style='padding:10px 14px;font-size:20px;'>{badge}</td>"
            f"<td style='padding:10px 14px;font-weight:600;'>{_esc(w.get('team_name') or '')}</td>"
            f"<td style='padding:10px 14px;color:#e8503a;font-weight:700;'>{score_txt}</td>"
            f"<td style='padding:10px 14px;color:#aaaaaa;'>{prize or '—'}</td>"
            f"</tr>"
        )
    body = "".join(rows) or "<tr><td colspan='4' style='padding:14px;color:#888;'>No winners.</td></tr>"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Winners — {_esc(event.name)}</title></head>
<body style="margin:0;background:#0a0a0a;font-family:Inter,system-ui,-apple-system,'Segoe UI',sans-serif;color:#f5f5f5;">
<div style="max-width:760px;margin:0 auto;padding:28px;">
  <div style="padding:24px;border-radius:16px;background:linear-gradient(135deg,#e8503a,#d4432e);color:#fff;">
    <h1 style="margin:0;font-size:26px;">🏆 Winners</h1>
    <p style="margin:6px 0 0;font-size:15px;opacity:0.92;">{_esc(event.name)}</p>
  </div>
  <table style="width:100%;border-collapse:collapse;margin-top:22px;font-size:14px;">
    <thead><tr style="text-align:left;color:#888888;border-bottom:1px solid #222222;">
      <th style="padding:8px 14px;">Rank</th><th style="padding:8px 14px;">Team</th>
      <th style="padding:8px 14px;">Score</th><th style="padding:8px 14px;">Prize</th>
    </tr></thead>
    <tbody>{body}</tbody>
  </table>
  <p style="text-align:center;color:#555555;font-size:12px;margin-top:28px;">Generated by EKAM · Team EKAM</p>
</div></body></html>"""


async def _latest_round(db: AsyncSession, event_id) -> Round | None:
    return (
        await db.execute(
            select(Round)
            .where(Round.event_id == event_id)
            .order_by(Round.created_at.desc())
        )
    ).scalars().first()


async def _team_members(db: AsyncSession, team_id) -> list[tuple[str, str]]:
    """(name, email) for each member, so each winner certificate carries the
    individual holder's name rather than just the team name."""
    rows = (
        await db.execute(
            select(Participant.name, Participant.email)
            .join(TeamMember, TeamMember.participant_id == Participant.id)
            .where(TeamMember.team_id == team_id)
        )
    ).all()
    return [(r[0] or "Participant", r[1]) for r in rows if r[1]]


async def propose_winners(
    db: AsyncSession,
    event_id,
    top_n: int = 3,
    round_id=None,
) -> dict:
    """Return the top-N teams (by final score) from a round's leaderboard."""
    rnd = None
    if round_id:
        rnd = (
            await db.execute(
                select(Round).where(Round.id == round_id, Round.event_id == event_id)
            )
        ).scalars().first()
    if rnd is None:
        rnd = await _latest_round(db, event_id)

    if rnd is None:
        return {"round_id": None, "winners": []}

    # Tournament round: the winners come from the bracket result (champion,
    # runner-up, …), not a submission leaderboard.
    from app.models.match import Match

    is_bracket = (
        await db.execute(select(Match.id).where(Match.round_id == rnd.id).limit(1))
    ).scalars().first()
    if is_bracket is not None:
        from app.services.bracket_service import bracket_standings

        standings = await bracket_standings(db, rnd.id)
        winners = [
            {
                "rank": s["rank"],
                "team_id": s["team_id"],
                "team_name": s["team_name"],
                "score": float(s["score"]),
            }
            for s in standings[: max(0, top_n)]
        ]
        return {"round_id": str(rnd.id), "winners": winners}

    leaderboard = await generate_leaderboard_service(db, rnd.id)

    winners = []
    for rank, submission in enumerate(leaderboard[: max(0, top_n)], start=1):
        team = (
            await db.execute(select(Team).where(Team.id == submission.team_id))
        ).scalars().first()
        winners.append(
            {
                "rank": rank,
                "team_id": str(submission.team_id),
                "team_name": team.name if team else str(submission.team_id)[:8],
                "score": float(submission.final_score or 0.0),
            }
        )

    return {"round_id": str(rnd.id), "winners": winners}


async def finalize_winners(
    db: AsyncSession,
    event_id,
    winners: list[dict],
    requested_by: str,
) -> dict:
    """Persist the confirmed winners and send announcement + certificate emails."""
    event = (
        await db.execute(select(Event).where(Event.id == event_id))
    ).scalars().first()
    if not event:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Event not found")

    if not winners:
        raise HTTPException(status_code=400, detail="No winners provided")

    # Persist as a report so it shows on the Reports page and survives.
    report = ReportModel(
        event_id=event_id,
        title=f"Winners — {event.name}",
        type="winners",
        data={"winners": winners, "report_html": _winners_report_html(event, winners)},
    )
    db.add(report)
    await db.commit()

    sent = 0
    winner_emails: set[str] = set()  # so they don't also get a participation cert
    for w in winners:
        rank = int(w.get("rank") or 0)
        team_id = w.get("team_id")
        prize = w.get("prize") or ""
        if not team_id:
            continue

        members = await _team_members(db, team_id)
        if not members:
            continue
        winner_emails.update(email for _, email in members if email)

        place = _ordinal(rank) if rank else "a winning"
        team_name = w.get("team_name") or "your team"

        prize_line = f"\n\nPrize: {prize}" if prize else ""
        subject = f"🏆 Congratulations! {team_name} won {place} place in {event.name}"
        body_text = (
            f"Congratulations {team_name}!\n\n"
            f"Your team secured {place} place in {event.name}.{prize_line}\n\n"
            f"Our team will contact you shortly regarding prize distribution and "
            f"next steps. Your winner certificate is attached.\n\n"
            f"Team EKAM"
        )
        body_html = (
            f"<p>Congratulations <strong>{team_name}</strong>!</p>"
            f"<p>Your team secured <strong>{place} place</strong> in "
            f"<strong>{event.name}</strong>."
            + (f" Prize: <strong>{prize}</strong>." if prize else "")
            + "</p>"
            f"<p>Our team will contact you shortly regarding <strong>prize "
            f"distribution and next steps</strong>. Your winner certificate is "
            f"attached.</p><p>Team EKAM</p>"
        )

        for member_name, email in members:
            # Per-member certificate so the holder's own name is on it (the
            # winning team is named in the achievement line).
            certificate_html = generate_certificate_html(
                participant_name=member_name,
                competition_name=event.name,
                achievement=f"{place} Place Winner — {team_name}",
            )
            ok = await send_direct_email(
                to=email,
                subject=subject,
                body_html=body_html,
                body_text=body_text,
                attachments={
                    f"winner_certificate_{member_name}.html".replace(" ", "_"):
                    certificate_html.encode("utf-8"),
                },
            )
            if ok:
                sent += 1

    # Participation certificates to everyone (best-effort).
    try:
        from app.email_triggers import on_certificate_distribution

        await on_certificate_distribution(
            event=event,
            db=db,
            requested_by=requested_by,
            achievement="Participation",
            exclude_emails=winner_emails,
        )
    except Exception as exc:
        print(f"[winner_service] participation certificate distribution failed: {exc}")

    return {
        "message": f"Winners announced. {sent} winner email(s) sent.",
        "report_id": str(report.id),
        "winners": winners,
    }
