"""describe_changes

Revision ID: 1005446f35bf
Revises: 991eee84c21f
Create Date: 2026-06-02 18:07:53.085252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1005446f35bf'
down_revision: Union[str, Sequence[str], None] = '991eee84c21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_criteria_round_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubric_criteria',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('round_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('rubric_criteria_round_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rubric_criteria_pkey'))
    )
    op.create_index(op.f('ix_rubric_criteria_round_id'), 'rubric_criteria', ['round_id'], unique=False)
    # ### end Alembic commands ###
