"""Add phase 3 to 8 models

Revision ID: 55919fb22c3c
Revises: 8fe9c392d17c
Create Date: 2026-05-29 03:20:52.362861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55919fb22c3c'
down_revision: Union[str, Sequence[str], None] = '8fe9c392d17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
