"""major auth workflow refactor

Revision ID: 8fe9c392d17c
Revises: a7338db06cab
Create Date: 2026-05-29 03:07:39.847442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fe9c392d17c'
down_revision: Union[str, Sequence[str], None] = 'a7338db06cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('organizer', 'admin', 'participant', 'judge', name='ownertype'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_type', sa.Enum('MAGIC_LINK', 'OTP', 'INVITATION', 'PASSWORDLESS_LOGIN', 'REFRESH_TOKEN', name='tokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_owner_id'), 'auth_tokens', ['owner_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=True)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('organizer', 'admin', 'participant', 'judge', name='ownertype'), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_owner_id'), 'otp_codes', ['owner_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('organizer', 'admin', 'participant', 'judge', name='ownertype'), nullable=False),
    sa.Column('jwt_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_jwt_id'), 'user_sessions', ['jwt_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_owner_id'), 'user_sessions', ['owner_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('team_formation', 'judge_assignment', 'email_batch', 'leaderboard_publish', 'stage_transition', 'progression', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'revised', name='approvalstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_event_id'), 'approval_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_type'), 'approval_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('info', 'alert', 'action_required', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('email_type', sa.Enum('otp', 'magic_link', 'invitation', 'team_assignment', 'stage_update', 'reminder', 'result', 'progression', name='emailtype'), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_html', sa.String(), nullable=True),
    sa.Column('body_text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'failed', name='emailstatus'), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_email_type'), 'email_drafts', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_drafts_event_id'), 'email_drafts', ['event_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_recipient_email'), 'email_drafts', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_drafts_status'), 'email_drafts', ['status'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.Enum('score_variance', 'bias_detected', 'time_anomaly', name='anomalytype'), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_event_id'), 'anomalies', ['event_id'], unique=False)
    op.drop_column('judges', 'otp_expiry')
    op.drop_column('judges', 'otp_code')
    op.drop_column('participants', 'otp_expiry')
    op.drop_column('participants', 'otp_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('otp_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('judges', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('judges', sa.Column('otp_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_anomalies_event_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_email_drafts_status'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_recipient_email'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_event_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_email_type'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_event_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_user_sessions_owner_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jwt_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_otp_codes_owner_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_owner_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
