"""add unique constraints

Revision ID: a7338db06cab
Revises: f1935f7791db
Create Date: 2026-05-27 17:07:04.121339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7338db06cab'
down_revision: Union[str, Sequence[str], None] = 'f1935f7791db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_judge_team_round', 'judge_assignments', ['judge_id', 'team_id', 'round_id'])
    op.create_unique_constraint('uq_event_judge_email', 'judges', ['event_id', 'email'])
    op.create_unique_constraint('uq_event_participant_email', 'participants', ['event_id', 'email'])
    op.create_unique_constraint('uq_team_participant', 'team_members', ['team_id', 'participant_id'])
    op.create_unique_constraint('uq_event_team_name', 'teams', ['event_id', 'name'])
    op.create_unique_constraint('uq_event_theme_name', 'themes', ['event_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_theme_name', 'themes', type_='unique')
    op.drop_constraint('uq_event_team_name', 'teams', type_='unique')
    op.drop_constraint('uq_team_participant', 'team_members', type_='unique')
    op.drop_constraint('uq_event_participant_email', 'participants', type_='unique')
    op.drop_constraint('uq_event_judge_email', 'judges', type_='unique')
    op.drop_constraint('uq_judge_team_round', 'judge_assignments', type_='unique')
    # ### end Alembic commands ###
